# Используем базовый образ Node.js
FROM node:20

# Указываем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходники
COPY . .

# Запускаем приложение
CMD ["npm", "run", "dev"]